'use client';
import {useEffect,useState} from 'react';import api from '../../../services/api';import PageHeader from '../../../components/PageHeader';import DataTable from '../../../components/DataTable';import Pagination from '../../../components/Pagination';import Modal from '../../../components/Modal';import StatusBadge from '../../../components/StatusBadge';import {toast} from 'sonner';
const blank={name:'',email:'',username:'',phone:'',role:'COORDINATOR',status:'ACTIVE',password:'ChangeMe123!'};
export default function UsersPage(){const [rows,setRows]=useState([]),[page,setPage]=useState(1),[pages,setPages]=useState(1),[search,setSearch]=useState(''),[role,setRole]=useState(''),[modal,setModal]=useState(false),[form,setForm]=useState(blank),[editId,setEditId]=useState(null);
const load=async()=>{const r=await api.get('/users',{params:{page,limit:10,search,role}});setRows(r.data.data);setPages(r.data.pagination.pages)};useEffect(()=>{load().catch(()=>toast.error('Failed to load users'))},[page,search,role]);
const save=async e=>{e.preventDefault();try{if(editId)await api.patch(`/users/${editId}`,form);else await api.post('/users',form);toast.success(editId?'User updated':'User created');setModal(false);setForm(blank);setEditId(null);load()}catch(e){toast.error(e.response?.data?.message||'Save failed')}};
const edit=r=>{setEditId(r._id);setForm({name:r.name,email:r.email,username:r.username,phone:r.phone||'',role:r.role,status:r.status,password:''});setModal(true)};
const status=async(r,s)=>{try{await api.patch(`/users/${r._id}/status`,{status:s});toast.success('Status updated');load()}catch(e){toast.error(e.response?.data?.message||'Failed')}};
const columns=[{key:'name',label:'Name'},{key:'email',label:'Email'},{key:'username',label:'Username'},{key:'role',label:'Role',render:r=><StatusBadge value={r.role}/>},{key:'status',label:'Status',render:r=><StatusBadge value={r.status}/>},{key:'lastLogin',label:'Last Login',render:r=>r.lastLogin?new Date(r.lastLogin).toLocaleString():'Never'},{key:'actions',label:'Actions',render:r=><div className="row-actions">{r.role!=='STUDENT'&&<button className="btn btn-secondary" onClick={()=>edit(r)}>Edit</button>}<button className="btn btn-secondary" onClick={()=>status(r,r.status==='ACTIVE'?'SUSPENDED':'ACTIVE')}>{r.status==='ACTIVE'?'Suspend':'Activate'}</button><button className="btn btn-secondary" onClick={async()=>{const password=prompt('Temporary password','ChangeMe123!');if(!password)return;try{await api.post(`/users/${r._id}/reset-password`,{password});toast.success('Password reset')}catch(e){toast.error(e.response?.data?.message||'Reset failed')}}}>Reset Password</button></div>}];
return <div className="page"><PageHeader title="Users" description="Create and manage system accounts." action={<button className="btn btn-primary" onClick={()=>{setForm(blank);setEditId(null);setModal(true)}}>Create User</button>}/><div className="toolbar"><input className="input" placeholder="Search users..." value={search} onChange={e=>{setPage(1);setSearch(e.target.value)}}/><select className="select" value={role} onChange={e=>{setPage(1);setRole(e.target.value)}}><option value="">All roles</option><option>ADMIN</option><option>COORDINATOR</option><option>STUDENT</option></select></div><DataTable columns={columns} rows={rows}/><Pagination page={page} pages={pages} onPage={setPage}/><Modal open={modal} title={editId?'Edit User':'Create User'} onClose={()=>setModal(false)}><form onSubmit={save} className="form-grid"><div><label className="label">Name</label><input className="input" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div><label className="label">Email</label><input className="input" type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><div><label className="label">Username</label><input className="input" required value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/></div><div><label className="label">Phone</label><input className="input" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></div><div><label className="label">Role</label><select className="select" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option>ADMIN</option><option>COORDINATOR</option></select></div><div><label className="label">Status</label><select className="select" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>ACTIVE</option><option>INACTIVE</option><option>SUSPENDED</option></select></div>{!editId&&<div style={{gridColumn:'1/-1'}}><label className="label">Temporary Password</label><input className="input" type="password" minLength={8} required value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></div>}<div style={{gridColumn:'1/-1'}}><button className="btn btn-primary">Save User</button></div></form></Modal></div>}
